// Knowledge-check pool for one-eighty. Server-side only (underscore path, not a route).
// Answers never leave the server; /api/check strips them before sending questions.
export default [
  {
    "id": "q1",
    "question": "The briefing forecast improvement from the west, but Johnstown was reporting IFR and a Skylane had turned back at the Allegheny Front. How should you read that conflict?",
    "options": [
      "Trust the forecast, because it is the official product and the observations are only snapshots.",
      "Treat the observations as the ground truth for now, because the improvement was real but slower than forecast and the terrain was already in the cloud.",
      "Average the two, and plan to arrive halfway between the forecast and the observed times.",
      "Trust the pilot report only, because it is the most recent and the forecast is always a hedge."
    ],
    "answer": 1,
    "explanation": "The forecast was never wrong, it was early. The observations describe what you would actually fly into, and the improvement and the terrain were racing each other.",
    "source": "Preflight-Weather"
  },
  {
    "id": "q2",
    "question": "Why is the 180-degree turn cheap early in the flight and expensive late?",
    "options": [
      "Early on it costs only pride and a plan, but every mile adds cost until it becomes a turn flown on instruments you have not trusted since a hood four years ago.",
      "Early on the turn is legal, and later it requires a clearance from ATC.",
      "Fuel burn rises with each mile, so a late turn leaves you short of reserves at the alternate.",
      "A late turn is fine as long as you are still in visual conditions, so the timing matters little."
    ],
    "answer": 0,
    "explanation": "The turn's whole value is in its earliness. It only ever looks early in the debrief, so decide before the weather arrives.",
    "source": "Preflight-Escape"
  },
  {
    "id": "q3",
    "question": "In the notch, the cloud base sags and the road ahead disappears into it. What is the trap in the instinct to duck lower and keep going under the cloud?",
    "options": [
      "Lower altitude reduces engine cooling, and the powerplant may overheat.",
      "Descending under the base is prohibited in mountainous terrain.",
      "The terrain rises toward the cloud, so you lose your outs and run into things like the powerline strung across the top of the gap, with no way through except up into cloud.",
      "Flying low makes the horizon harder to see, which causes the leans."
    ],
    "answer": 2,
    "explanation": "Getting under leaves fifty feet of clear air and a powerline you see before you see the wires. The ground and the cloud are closing on each other, and you are in the middle.",
    "source": "Under_Wires"
  },
  {
    "id": "q4",
    "question": "What should you say to ATC when the weather is closing and you are a VFR pilot with no instrument rating, and why does calling early help?",
    "options": [
      "Say nothing until you are in cloud, so as not to tie up the frequency with a problem that may not happen.",
      "Ask only for a current altimeter setting, and save any admission for a real emergency.",
      "State plainly that you are a VFR pilot in deteriorating conditions and request assistance, because Approach can provide radar vectors, terrain awareness, and a calm voice while options remain.",
      "Request an IFR clearance directly, since controllers will not help VFR pilots who are not declaring an emergency."
    ],
    "answer": 2,
    "explanation": "The confession works everywhere except the last thirty seconds. Made from clear air it is a request, and made too late it becomes a rescue.",
    "source": "Preflight-Escape"
  },
  {
    "id": "q5",
    "question": "In cloud, your inner ear says the airplane is in a gentle right turn and the attitude indicator says wings level. What does the scenario teach about the disagreement?",
    "options": [
      "The inner ear sensation is generated by fluid physics and not by the airplane, so you believe the instruments as a discipline, even while the body objects.",
      "Split the difference and fly a shallow left bank until the sensations agree.",
      "Trust the body if the sensation persists for more than a minute, because the instruments may be failing.",
      "Close your eyes briefly to reset the inner ear, then scan the instruments again."
    ],
    "answer": 0,
    "explanation": "The leans are not a character flaw, they are plumbing. The instruments are the only crew member telling the truth in there.",
    "source": "End_Spiral"
  },
  {
    "id": "q6",
    "question": "What is the ridge-and-valley weather trap the scenario describes on this route?",
    "options": [
      "Winds accelerate through every valley, so the flight must be flown above the ridgetops.",
      "The valleys stay clear all night while the ridges are always in the clear.",
      "Terrain rises westbound while ceilings fall westbound, so the two cross near the Allegheny Front, and west of the crossing there is no room between cloud and granite.",
      "Ceilings rise with terrain, so the higher ground is always the safest place to cross."
    ],
    "answer": 2,
    "explanation": "East of the crossing you fly in a comfortable sandwich. West of it, the filling is granite, and the last easy out was Altoona, twenty-five miles into an eighty-mile trip.",
    "source": "Preflight-Route"
  },
  {
    "id": "q7",
    "question": "Caught between the cloud deck and the plateau with about two hundred feet of clear air, the pilot lands in a pasture. How does the scenario judge that outcome?",
    "options": [
      "As a failure, because a certificated pilot should have been able to climb back into cloud on the gauges.",
      "As a good outcome, because a controlled arrival on a chosen surface beats a blind climb or a crawl into terrain, and a field you chose beats any sky you did not.",
      "As acceptable only if the airplane is undamaged, otherwise as a violation.",
      "As a poor choice, because the pilot should have hunted onward for a longer, better field."
    ],
    "answer": 1,
    "explanation": "The precautionary landing is not the consolation prize, it is the podium. Land the airplane while it is still yours to land.",
    "source": "End_Grass"
  },
  {
    "id": "q8",
    "question": "The scrub-and-drive ending describes the go/no-go as a bet with a specific asymmetry. Which principle does that support?",
    "options": [
      "Personal minimums exist to take capped-upside, uncapped-downside decisions out of the moment's hands, because flying saves about two hours if you win and the loss is unbounded if you do not.",
      "Personal minimums should be adjusted upward whenever a friend is waiting at the destination.",
      "Personal minimums matter only for pilots below a certain number of hours.",
      "Personal minimums are best decided at the airplane after reading the latest observations, rather than in advance."
    ],
    "answer": 0,
    "explanation": "Hindsight only sees one branch, so Sunday's blue sky will make the scrub look excessive. The minimums were written for exactly this kind of bet.",
    "source": "End_Scrub_Drive"
  },
  {
    "id": "q9",
    "question": "A VFR pilot with no instrument rating flies into cloud. What does the scenario teach as the trained response?",
    "options": [
      "Descend at once to get back under the cloud while the ground is still there.",
      "Pull the power back and hold the current heading until the cloud ends.",
      "Fly by the sensations of the body, since the first instinct is usually right.",
      "Eyes on the attitude indicator, wings level, then a standard-rate 180 by the numbers to exit the way you came in, and call Approach with the whole truth."
    ],
    "answer": 3,
    "explanation": "The syllabus taste of instrument flying exists for this one turn. Pushing down for the ground is the choice that ends in the pasture or the spiral.",
    "source": "IMC_Entry"
  },
  {
    "id": "q10",
    "question": "Coop's texts said there was no rush and that the couch was free tomorrow too. What does the scenario say about the pressure to make the dinner?",
    "options": [
      "The pressure came from the host, and the pilot was right to weigh it heavily as a matter of loyalty.",
      "The pressure was entirely in-house: get-there-itis dressed as loyalty, when the friends would have been happy with a pilot who drove or arrived late.",
      "Pressure from passengers is the only kind that counts as a hazardous attitude.",
      "There was no pressure, because the pilot had already decided to fly before the texts arrived."
    ],
    "answer": 1,
    "explanation": "Coop applied no pressure at all, and nobody at the table thought less of a pilot for driving. The mission was dinner with people you love, and the mission can complete by road.",
    "source": "Delay_Watch"
  }
];
